[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

[buildPlans.IosevkaCustom.variants.design]
tilde = "low"
asterisk = "penta-low"
underscore = "high"
caret = "high"
paren = "flat-arc"
brace = "curly-flat-boundary"
ampersand = "closed"
at = "fourfold-solid-inner-tall"
dollar = "through"
cent = "through"
percent = "rings-segmented-slash"
question = "smooth"
pilcrow = "low"
micro-sign = "toothed-serifed"
lig-ltgteq = "slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaCustom.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustom.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaCustom.weights.Heavy]
shape = 900
menu = 900
css = 900
